source 'http://rubygems.org'

gem "susy", "2.2.1"
gem "compass-core"
gem "breakpoint"
gem "haml"
gem "sass", "3.4.9"
gem "nanoc", "3.7.4"
gem "RedCloth"
gem "redcarpet"
gem "builder"
gem "adsf"
gem "nokogiri"
gem "pygments.rb", "0.6.0"
gem "guard"
gem "guard-livereload"
gem "guard-nanoc"
gem "asciidoctor"
gem "nanoc-asciidoctor"
gem "nokogiri"
